build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: OptiVolt"
  org.opencontainers.image.description: "Plan and control Victron ESS with forecasts & dynamic tariffs"
  org.opencontainers.image.source: "https://github.com/vervoto1/optivolt"
  org.opencontainers.image.licenses: "MIT"
